# Generated by Django 3.2.9 on 2021-12-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211205_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritebook',
            name='edition_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
